import { useInMemoryDb } from '../index.js'
import { Readable } from 'stream'
import { parse } from 'JSONStream'
import assert from 'assert'

const collectStream = (stream: Readable): Promise<any[]> =>
  new Promise((resolve, reject) => {
    const results: any[] = []
    stream.on('data', (data) => results.push(data))
    stream.on('end', () => resolve(results))
    stream.on('error', reject)
  })

const streamData = (stream: Readable): Promise<string> =>
  new Promise((resolve, reject) => {
    let data = ''
    stream.on('data', (chunk) => { data += chunk })
    stream.on('end', () => resolve(data))
    stream.on('error', reject)
  })

const jt400 = useInMemoryDb()
describe('hsql in memory', () => {
  beforeEach(() => {
    return jt400
      .update(
        'create table testtbl (ID DECIMAL(15, 0) GENERATED BY DEFAULT AS IDENTITY(START WITH 1234567891234), NAME VARCHAR(300), START DATE, STAMP TIMESTAMP, PRIMARY KEY(ID))',
      )
      .then(() =>
        jt400.update("insert into testtbl (NAME) values('Foo bar baz')"),
      )
  })

  afterEach(() => {
    return jt400.update('drop table testtbl')
  })

  describe('query', () => {
    it('should be in memory', () => {
      assert.strictEqual(jt400.isInMemory(), true)
    })

    it('should select form testtbl', async () => {
      const res = await jt400.query<any>('select * from testtbl')
      assert.strictEqual(res.length, 1)
    })

    it('should use column alias when selecting', async () => {
      const res = await jt400.query<any>('select ID, NAME MYNAME from testtbl')
      assert.ok('MYNAME' in res[0])
    })

    it('should query as stream', async () => {
      const stream = jt400.createReadStream('select * from testtbl')
      const rows = await collectStream(stream.pipe(parse([true])))
      assert.strictEqual(rows.length, 1)
    })

    it('should fail queryAsStream with oops error', async () => {
      const stream = jt400.createReadStream('select * from testtbl', ['a'])
      await assert.rejects(
        collectStream(stream),
        (err: Error) => {
          assert.strictEqual(
            err.message,
            'Argumento incorrecto en una llamada JDBC: parameter index out of range: 1',
          )
          return true
        },
      )
    })
  })

  describe('insert', () => {
    it('should insert and return id', async () => {
      const res = await jt400.insertAndGetId(
        'insert into testtbl (NAME) values(?)',
        ['foo'],
      )
      assert.strictEqual(res, 1234567891235)
    })

    it('should insert list', async () => {
      const res = await jt400.insertList('testtbl', 'ID', [
        {
          NAME: 'foo',
        },
        {
          NAME: 'bar',
        },
      ])

      assert.deepStrictEqual(res, [1234567891235, 1234567891236])

      const select = await jt400.query('select * from testtbl')
      assert.strictEqual(select.length, 3)
    })

    it('should insert date and timestamp', async () => {
      const ids = await jt400.insertList('testtbl', 'ID', [
        {
          START: new Date().toISOString().slice(0, 10),
          STAMP: new Date(),
        },
      ])

      assert.deepStrictEqual(ids, [1234567891235])
    })

    it('should create write stream', async () => {
      const dataStream = new Readable({ objectMode: true })
      let c = 97
      dataStream._read = function () {
        dataStream.push([String.fromCharCode(c++)])
        if (c > 'z'.charCodeAt(0)) {
          dataStream.push(null)
        }
      }

      const ws = jt400.createWriteStream(
        'insert into testtbl (NAME) VALUES(?)',
        { bufferSize: 10 },
      )

      await new Promise<void>((resolve, reject) => {
        dataStream.pipe(ws).on('finish', resolve).on('error', reject)
      })

      const res = await jt400.query('select name from testtbl')
      assert.strictEqual(res.length, 27)
    })
  })

  describe('queryCursor', () => {
    it('should iterate rows via async generator', async () => {
      await jt400.update("insert into testtbl (NAME) values('Second')")
      const rows: unknown[] = []
      for await (const row of jt400.queryCursor('SELECT NAME FROM testtbl ORDER BY NAME')) {
        rows.push(row)
      }
      assert.strictEqual(rows.length, 2)
    })

    it('should return empty iterable for no results', async () => {
      const rows: unknown[] = []
      for await (const row of jt400.queryCursor("SELECT NAME FROM testtbl WHERE NAME = 'nonexistent'")) {
        rows.push(row)
      }
      assert.strictEqual(rows.length, 0)
    })
  })

  describe('batch update', () => {
    it('should insert batch', async () => {
      const res = await jt400.batchUpdate(
        'insert into testtbl (NAME,START) values(?, ?)',
        [
          ['foo', '2015-01-02'],
          ['bar', '2015-03-04'],
        ],
      )

      assert.deepStrictEqual(res, [1, 1])
    })

    it('should handle empty batch', async () => {
      const res = await jt400.batchUpdate('insert into testtbl (NAME) values(?)', [])
      assert.deepStrictEqual(res, [])
    })

    it('should fail insert batch with oops-error', () => {
      const sql = 'insert into testtbl (NAME,START) values(?, ?)'
      const params = [
        ['foo', '2015-01-02'],
        ['bar', '2015-03-04'],
        ['a', 'b', 'c', 'd'],
      ]

      return jt400
        .batchUpdate(sql, params)
        .then(() => {
          throw new Error('wrong error')
        })
        .catch((error) => {
          assert.strictEqual(
            error.message,
            'excepción de datos: formato fecha/hora incorrecto',
          )
          assert.ok(error.cause.stack.includes('JdbcJsonClient.setParams'))
          assert.strictEqual(error.context.sql, sql)
          assert.deepStrictEqual(error.context.params, params)
          assert.strictEqual(error.category, 'ProgrammerError')
        })
    })
  })

  describe('pgm call mock', () => {
    let callFoo
    let input

    beforeEach(() => {
      callFoo = jt400.defineProgram({
        programName: 'foo',
        paramsSchema: [
          {
            name: 'bar',
            size: 10,
          },
          {
            name: 'baz',
            size: 9,
            decimals: 2,
          },
        ],
      })

      input = {
        bar: 'a',
        baz: 10,
      }
    })

    it('should return input by default', async () => {
      const res = await callFoo(input)
      assert.deepStrictEqual(res, input)
    })

    it('should register mock', async () => {
      jt400.mockPgm('foo', (input) => {
        input.baz = 20
        return input
      })

      const res = await callFoo(input)
      assert.strictEqual(res.baz, 20)
    })
  })

  describe('should mock ifs', () => {
    it('should get metadata', async () => {
      const metadata = await jt400.ifs().fileMetadata('/foo/bar.txt')
      assert.deepStrictEqual(metadata, {
        exists: false,
        length: 0,
      })
    })
  })

  describe('execute', () => {
    it('should get metadata', async () => {
      const statement = await jt400.execute('select * from testtbl')
      const metadata = await statement.metadata()

      assert.deepStrictEqual(metadata, [
        {
          name: 'ID',
          typeName: 'DECIMAL',
          precision: 15,
          scale: 0,
        },
        {
          name: 'NAME',
          typeName: 'VARCHAR',
          precision: 300,
          scale: 0,
        },
        {
          name: 'START',
          typeName: 'DATE',
          precision: 10,
          scale: 0,
        },
        {
          name: 'STAMP',
          typeName: 'TIMESTAMP',
          precision: 26,
          scale: 6,
        },
      ])
    })

    it('should get result as stream', async () => {
      const statement = await jt400.execute('select * from testtbl')
      assert.strictEqual(statement.isQuery(), true)
      const data = await streamData(statement.asStream())
      assert.strictEqual(data, '[["1234567891234","Foo bar baz",null,null]]')
    })

    it('should get result as object stream', async () => {
      const statement = await jt400.execute('select * from testtbl')
      const stream = await statement.asObjectStream()
      const rows = await collectStream(stream)
      assert.deepStrictEqual(rows, [
        {
          ID: '1234567891234',
          NAME: 'Foo bar baz',
          START: null,
          STAMP: null,
        },
      ])
    })

    it('should get result as array', async () => {
      const statement = await jt400.execute('select * from testtbl')
      const data = await statement.asArray()
      assert.deepStrictEqual(data, [
        ['1234567891234', 'Foo bar baz', null, null],
      ])
    })

    it('should get result as iterable', async () => {
      const statement = await jt400.execute('select * from testtbl')
      const rows = statement.asIterable()
      let count = 0
      for await (const row of rows) {
        count++
        assert.deepStrictEqual(row, [
          '1234567891234',
          'Foo bar baz',
          null,
          null,
        ])
      }
      assert.strictEqual(count, 1)
    })

    it('should pipe to JSONStream', async () => {
      const inserts: number[] = []
      for (let i = 1; i < 110; i++) inserts.push(i)

      await inserts.reduce(
        (memo, item) =>
          memo.then(() =>
            jt400.update('insert into testtbl (NAME) values(?)', ['n' + item]),
          ),
        Promise.resolve() as Promise<any>,
      )

      const statement = await jt400.execute('select NAME from testtbl order by ID')
      const stream = statement.asStream().pipe(parse([true]))
      const res = await collectStream(stream)

      assert.strictEqual(res.length, 110)
      res.forEach((row, index) => {
        if (index > 0) {
          assert.deepStrictEqual(row[0], 'n' + index)
        }
      })
    })

    it('should get update count', async () => {
      const statement = await jt400.execute('update testtbl set NAME=?', [
        'testing',
      ])
      assert.strictEqual(statement.isQuery(), false)
      const updated = await statement.updated()
      assert.strictEqual(updated, 1)
    })

    it('should close stream', async () => {
      const inserts: number[] = []
      for (let i = 1; i < 40; i++) inserts.push(i)

      await Promise.all(
        inserts.map((item) =>
          jt400.update('insert into testtbl (NAME) values(?)', ['n' + item]),
        ),
      )

      const statement = await jt400.execute('select NAME from testtbl')
      const res: any[] = []

      await new Promise<void>((resolve, reject) => {
        const stream = statement
          .asStream({ bufferSize: 10 })
          .pipe(parse([true]))

        stream.on('data', (row) => {
          res.push(row)
          if (res.length >= 10) {
            statement.close()
          }
        })

        stream.on('end', resolve)
        stream.on('error', reject)
      })

      assert.ok(res.length < 21)
    })
  })

  describe('metadata', () => {
    it('should return table metadata as stream', async () => {
      const stream = jt400.getTablesAsStream({ schema: 'PUBLIC' })
      const schema = await collectStream(stream)
      assert.deepStrictEqual(schema, [
        {
          schema: 'PUBLIC',
          table: 'TESTTBL',
          remarks: '',
        },
      ])
    })

    it('should return columns', async () => {
      const res = await jt400.getColumns({
        schema: 'PUBLIC',
        table: 'TESTTBL',
      })

      assert.deepStrictEqual(res, [
        {
          name: 'ID',
          typeName: 'DECIMAL',
          precision: 15,
          scale: 0,
        },
        {
          name: 'NAME',
          typeName: 'VARCHAR',
          precision: 300,
          scale: 0,
        },
        {
          name: 'START',
          typeName: 'DATE',
          precision: 10,
          scale: 0,
        },
        {
          name: 'STAMP',
          typeName: 'TIMESTAMP',
          precision: 26,
          scale: 0,
        },
      ])
    })

    it('should return primary key', async () => {
      const res = await jt400.getPrimaryKeys({
        table: 'TESTTBL',
      })

      assert.strictEqual(res.length, 1)
      assert.strictEqual(res[0].name, 'ID')
    })
  })

  describe('transaction', () => {
    it('should commit', () => {
      let rowId
      return jt400
        .transaction((transaction) => {
          return transaction
            .insertAndGetId(
              "insert into testtbl (NAME) values('Transaction 1')",
            )
            .then((res) => {
              rowId = res
              return transaction.update(
                "update testtbl set NAME='Transaction 2' where id=?",
                [rowId],
              )
            })
        })
        .then(() =>
          jt400.query<any>('select NAME from testtbl where id=?', [rowId]),
        )
        .then((res) => {
          assert.deepStrictEqual(res[0].NAME, 'Transaction 2')
        })
    })

    it('should rollback', () => {
      const fakeError = new Error('fake error')
      let rowId
      return jt400
        .transaction((transaction) => {
          return transaction
            .insertAndGetId(
              "insert into testtbl (NAME) values('Transaction 1')",
            )
            .then((res) => {
              rowId = res
              throw fakeError
            })
        })
        .catch((err) => {
          assert.strictEqual(err, fakeError)
        })
        .then(() => jt400.query('select NAME from testtbl where id=?', [rowId]))
        .then((res) => {
          assert.strictEqual(res.length, 0)
        })
    })

    it('should batch update', async () => {
      const res = await jt400.transaction((transaction) => {
        return transaction.batchUpdate('insert into testtbl (NAME) values(?)', [
          ['Foo'],
          ['Bar'],
        ])
      })
      assert.deepStrictEqual(res, [1, 1])
    })
  })
})
